/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface _SERVICE {
  /**
   * / Fetches test data for a given testId via HTTP outcall.
   * / Uses a placeholder endpoint; real 5G endpoint can be substituted.
   */
  'fetchTestData' : ActorMethod<[string], string>,
  /**
   * / Retrieves (deviceId, results) for a given testId.
   */
  'getTestData' : ActorMethod<[string], [] | [[string, string]]>,
  /**
   * / Stores deviceId and results keyed by testId.
   */
  'setTestData' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Triggers the HTTP outcall for the given testId and returns the raw response.
   */
  'startFetching' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformArgs], HttpRequestResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];