/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});

export const idlService = IDL.Service({
  'fetchTestData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getTestData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
    ),
  'setTestData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'startFetching' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func([TransformArgs], [HttpRequestResult], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  
  return IDL.Service({
    'fetchTestData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getTestData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
      ),
    'setTestData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'startFetching' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func([TransformArgs], [HttpRequestResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };